# jwt 설정
jwt:
  access:
    token:
      secret: jggQLY/OR1b9F3iNSx9HXPQhsfMXjx6jnWGKTr6F8/YwJcY=
      expiration: 3600000  # 1 hour in milliseconds
  refresh:
    token:
      secret: zr7/kYanZMg3mtWRTSoIDUNTPO1o3a9a1Mv2eUH1geKjAng=
      expiration: 2592000000  # 30 days in milliseconds